export const ORDER_FROM_HM = 'ORDER_FROM_HM'
export const ORDER_FROM_MEDIAMARKET = 'ORDER_FROM_MEDIAMARKET'

export const REMOVE_ONE_FROM_HM = 'REMOVE_ONE_FROM_HM'
export const REMOVE_ALL_FROM_HM = 'REMOVE_ALL_FROM_HM'
export const REMOVE_ONE_FROM_MEDIAMARKET = 'REMOVE_ONE_FROM_MEDIAMARKET'
export const REMOVE_ALL_FROM_MEDIAMARKET = 'REMOVE_ALL_FROM_MEDIAMARKET'

export const CHECKOUT_FROM_MEDIAMARKET = 'CHECKOUT_FROM_MEDIAMARKET'
export const CHECKOUT_FROM_HM = 'CHECKOUT_FROM_MEDIAMARKET'


export const FETCH_HM_DATA = 'FETCH_HM_DATA'
export const FETCH_MEDIAMARKET_DATA = 'FETCH_MEDIAMARKET_DATA'








